const PDFDocument = require('pdfkit');

function money(value) {
  return `Rs. ${Number(value || 0).toFixed(2)}`;
}

function date(value) {
  return value ? new Date(value).toLocaleDateString('en-IN') : '-';
}

function line(doc, label, value) {
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(value == null || value === '' ? '-' : String(value));
}

function generateInvoicePdf({ invoiceNumber, payment, booking, recipient }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc
      .font('Helvetica-Bold')
      .fontSize(22)
      .fillColor('#008260')
      .text('CalxMap Finance Invoice');

    doc
      .moveDown(0.4)
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#64748b')
      .text('Generated for training payment management');

    doc.moveDown(1.5).fillColor('#0f172a').fontSize(12);
    line(doc, 'Invoice Number', invoiceNumber);
    line(doc, 'Generated Date', date(new Date().toISOString()));
    line(doc, 'Payment Type', payment.party_type === 'expert' ? 'Expert Payout' : 'Institute Collection');
    line(doc, 'Payment Status', payment.status || 'pending');

    doc.moveDown(1).font('Helvetica-Bold').fontSize(14).text('Recipient');
    doc.moveDown(0.4).fontSize(11);
    line(doc, 'Name', recipient?.name);
    line(doc, 'Email', recipient?.email);

    doc.moveDown(1).font('Helvetica-Bold').fontSize(14).text('Training');
    doc.moveDown(0.4).fontSize(11);
    line(doc, 'Project', booking?.projects?.title || booking?.project?.title || payment.project_id);
    line(doc, 'Booking ID', payment.booking_id);
    line(doc, 'Start Date', date(booking?.start_date));
    line(doc, 'End Date', date(booking?.end_date));
    line(doc, 'Expert', booking?.experts?.name || booking?.expert?.name);
    line(doc, 'Institution', booking?.institutions?.name || booking?.institution?.name);

    doc.moveDown(1).font('Helvetica-Bold').fontSize(14).text('Calculation');
    doc.moveDown(0.6);
    const top = doc.y;
    const left = doc.x;
    const widths = [160, 130, 130, 120];
    const headers = ['Approved Hours', 'Hourly Rate', 'Calculated', 'Invoice Amount'];
    const values = [
      Number(payment.approved_hours || 0).toFixed(2),
      money(payment.hourly_rate_snapshot),
      money(payment.calculated_amount),
      money(payment.invoice_amount),
    ];

    doc.rect(left, top, widths.reduce((sum, width) => sum + width, 0), 24).fill('#ecfdf5');
    doc.fillColor('#064e3b').font('Helvetica-Bold').fontSize(10);
    let x = left;
    headers.forEach((header, index) => {
      doc.text(header, x + 8, top + 7, { width: widths[index] - 16 });
      x += widths[index];
    });
    doc.rect(left, top + 24, widths.reduce((sum, width) => sum + width, 0), 30).fill('#ffffff').stroke('#e2e8f0');
    doc.fillColor('#0f172a').font('Helvetica').fontSize(11);
    x = left;
    values.forEach((value, index) => {
      doc.text(value, x + 8, top + 33, { width: widths[index] - 16 });
      x += widths[index];
    });

    if (payment.notes) {
      doc.moveDown(4).font('Helvetica-Bold').fontSize(14).text('Notes');
      doc.moveDown(0.4).font('Helvetica').fontSize(11).text(payment.notes, { width: 480 });
    }

    doc
      .fontSize(9)
      .fillColor('#64748b')
      .text('This invoice was generated by CalxMap Super Admin finance workflow.', 48, 760, {
        align: 'center',
        width: 500,
      });

    doc.end();
  });
}

module.exports = {
  generateInvoicePdf,
};
